### ISSUE TITLE
fresco编解码的具体方案？

### ISSUE THREAD

**Issue by liganisme** [desmond1121/Fresco-Source-Analysis#1]
感谢写出那么优秀的分析，我一直有关注fresco，目前据我所知，除了良好的结构，其在效率上的优势也是巨大的，核心是减少gc，4.x上gc卡顿是很明显的。原理是利用ashmem机制，将bitmap不放在虚拟机堆内存，而且有共享native内存，lockpixels是可以将内存锁定、图片解码，但是共享是如何实现还未透彻，猜想是native通过lockpixels持有后，再配合bitmapfactory.options属性共用内存，不知是否正确，希望前辈能写文详解！

**Comment by desmond1121** [comment]
@liganisme 谢谢你的建议，基本上是这样的，fresco本地实现了内存池，在4.4以下机型通过`BitmapFactory.Options`的`inPurgeable`将其放入ashmem中。我之前的分析仅仅在结构上的大体理解，有时间的话我会再仔细研读源码深入分析:)

**Comment by liganisme** [comment]
感谢你的回复！
